version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule: { interval: weekly }
    groups:
      go: { patterns: ["*"] }
  - package-ecosystem: github-actions
    directories: ["/", "/action"]
    schedule: { interval: weekly }
    groups:
      actions: { patterns: ["*"] }
  - package-ecosystem: npm
    directory: /docs
    schedule: { interval: monthly }
    groups:
      docs: { patterns: ["*"] }
