// Command catalog writes the docs site's check catalog, one Markdown page per
// module, from the same Meta that `seta checks explain` prints.
//
//	go run ./internal/tools/catalog docs/src/content/docs/checks
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	_ "github.com/PeacexF/seta/checks/dns"
	_ "github.com/PeacexF/seta/checks/email"
	_ "github.com/PeacexF/seta/checks/http"
	_ "github.com/PeacexF/seta/checks/tls"
	"github.com/PeacexF/seta/internal/core"
	"github.com/PeacexF/seta/internal/registry"
)

var moduleTitles = map[string]string{
	"email": "Email",
	"tls":   "TLS",
	"http":  "HTTP",
	"dns":   "DNS",
}

func main() {
	if len(os.Args) != 2 {
		log.Fatal("usage: catalog <output-dir>")
	}
	dir := os.Args[1]
	if err := os.MkdirAll(dir, 0o755); err != nil {
		log.Fatal(err)
	}
	byModule := map[string][]core.Meta{}
	var modules []string
	for _, c := range registry.Default.All() {
		m := c.Meta()
		if _, ok := byModule[m.Module]; !ok {
			modules = append(modules, m.Module)
		}
		byModule[m.Module] = append(byModule[m.Module], m)
	}
	for _, mod := range modules {
		path := filepath.Join(dir, mod+".md")
		if err := os.WriteFile(path, []byte(page(mod, byModule[mod])), 0o644); err != nil {
			log.Fatal(err)
		}
	}
}

func page(module string, metas []core.Meta) string {
	title := moduleTitles[module]
	if title == "" {
		title = module
	}
	var b strings.Builder
	fmt.Fprintf(&b, "---\ntitle: %s checks\ndescription: Every check in the %s module, what it verifies, and how to fix findings.\n---\n\n", title, module)
	b.WriteString("<!-- Generated by `go run ./internal/tools/catalog`; edit the check's Meta instead. -->\n\n")
	b.WriteString("Run `seta checks explain <id>` for the same text in your terminal.\n\n")
	b.WriteString("| Check | Mode | Default severity | Finding |\n|---|---|---|---|\n")
	for _, m := range metas {
		fmt.Fprintf(&b, "| [`%s`](#%s) | %s | %s | %s |\n", m.ID, anchor(m.ID), m.Mode, m.Severity, esc(m.Title))
	}
	for _, m := range metas {
		fmt.Fprintf(&b, "\n## %s\n\n**%s** · %s · default severity **%s**", m.ID, esc(m.Title), m.Mode, m.Severity)
		if len(m.Aliases) > 0 {
			fmt.Fprintf(&b, " · formerly `%s`", strings.Join(m.Aliases, "`, `"))
		}
		fmt.Fprintf(&b, "\n\n%s\n\n**How to fix:** %s\n", esc(m.Description), esc(m.Remediation))
		if len(m.References) > 0 {
			b.WriteString("\n**References:**\n\n")
			for _, r := range m.References {
				fmt.Fprintf(&b, "- <%s>\n", r)
			}
		}
	}
	return b.String()
}

// anchor matches the heading IDs Starlight generates: dots are dropped.
func anchor(id string) string { return strings.ReplaceAll(id, ".", "") }

// esc keeps placeholders like <domain> from being parsed as HTML tags.
func esc(s string) string {
	return strings.NewReplacer("<", "&lt;", ">", "&gt;", "|", "\\|").Replace(s)
}
