events {}
http {
    server {
        listen 443 ssl;
        server_name mta-sts.tls.int.test;
        ssl_certificate     /certs/mta-sts.pem;
        ssl_certificate_key /certs/mta-sts.key;
        location = /.well-known/mta-sts.txt {
            default_type text/plain;
            alias /policy/mta-sts.txt;
        }
    }
}
